apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cringe
resources:
  - ../base
images:
  - name: IMAGES/APP
    newName: tomjtoth/cringe:0.9.0
patches:
  - path: pvc.yml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: cringe-db-pvc
