apiVersion: v1
kind: Pod
metadata:
  name: ${APP_NAMESPACE}-migrator
  namespace: ${APP_NAMESPACE}
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: ${APP_HOST}

  containers:
    - name: migrator
      image: alpine
      command: ["/bin/sh", "-c", "sleep 36000"]

      volumeMounts:
        - name: host
          mountPath: /data-on-host
        - name: pvc
          mountPath: /data-on-pvc

  volumes:
    - name: host
      hostPath:
        path: ${PATH_TO_DATA_ON_HOST}
    - name: pvc
      persistentVolumeClaim:
        claimName: ${PVC_NAME}
