apiVersion: apps/v1
kind: Deployment

metadata:
  name: cringe-dep
  labels:
    app: cringe

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cringe
  template:
    metadata:
      labels:
        app: cringe
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h cringe-db-svc -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
                echo "waiting for cringe-db-svc..."
                sleep 2
              done
          envFrom:
            - secretRef:
                name: cringe-secrets

      containers:
        - name: cringe
          image: IMAGES/APP
          imagePullPolicy: Always

          env:
            - name: REDIRECT_URL
              value: https://cringe.ttj.hu/api/auth/callback

            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@cringe-db-svc/$(POSTGRES_DB)

          envFrom:
            - secretRef:
                name: cringe-secrets

          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 80

          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cringe
  name: cringe-db-dep
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: cringe-db-pvc

      containers:
        - name: postgres
          image: postgres:alpine

          envFrom:
            - secretRef:
                name: cringe-secrets

          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/18/docker

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 2
            periodSeconds: 1
