apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cringe-db-pvc
  namespace: cringe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
