apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saldo
  namespace: argocd
spec:
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      namespace: staging-saldo
      jsonPointers:
        - /spec/volumeName
