apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-saldo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tomjtoth/kubernetes
    targetRevision: HEAD
    path: apps/saldo/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging-saldo

  ignoreDifferences:
    - group: "apps"
      kind: Deployment
      name: saldo-dep
      namespace: staging-saldo
      jsonPointers:
        - /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
