- op: add
  path: /spec/template/spec/containers/0/command
  value:
    - sh
    - -c
    - cp /app/data/prod.db /app/data/staging.db && exec node server.js

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DB_PATH
    value: /app/data/staging.db

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: AUTH_URL
    value: https://staging.saldo.ttj.hu/api/auth
