- op: replace
  path: /spec/template/spec/containers/0/env/0/value
  value: https://saldo.staging.ttj.hu/api/auth

- op: replace
  path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
  value: staging-saldo-pvc-dummy

- op: replace
  path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
  value: staging-saldo-secrets
