apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-saldo
resources:
  - ../base
  - rbac.yml
  - argo-hooks/pre-sync.yml
  - argo-hooks/post-sync.yml

patches:
  - path: deployment.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: saldo-dep
  - path: ingress.yml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: saldo-ing
  - path: pvc.yml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: saldo-pvc
images:
  - name: IMAGES/APP
    newName: tomjtoth/saldo:latest
