apiVersion: v1
kind: ServiceAccount
metadata:
  name: staging-saldo-hook
  namespace: staging-saldo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staging-saldo-hook
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "pods", "deployments"]
    verbs: ["get", "list", "create", "delete", "patch", "watch"]
  - apiGroups: ["longhorn.io"]
    resources: ["backupvolumes"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: staging-saldo-hook
subjects:
  - kind: ServiceAccount
    name: staging-saldo-hook
    namespace: staging-saldo
roleRef:
  kind: ClusterRole
  name: staging-saldo-hook
  apiGroup: rbac.authorization.k8s.io
