apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: saldo
resources:
  - ../base
patches:
  - path: deployment.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: saldo-dep
  - path: pvc.yml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: saldo-pvc
images:
  - name: IMAGES/APP
    newName: tomjtoth/saldo:1.3.4
